"""
ForgeIQ — Compliance Intelligence API
"""
from fastapi import APIRouter

router = APIRouter()


@router.get("/status")
async def get_compliance_status():
    return {
        "overall_score": 78.4,
        "audit_readiness": 72,
        "total_requirements": 245,
        "compliant": 156,
        "partial": 52,
        "non_compliant": 18,
        "missing": 19,
        "regulations": [
            {
                "id": "iso-45001",
                "name": "ISO 45001:2018",
                "description": "Occupational Health & Safety Management",
                "score": 92,
                "status": "compliant",
                "requirements_total": 48,
                "requirements_met": 44,
                "gaps": 4,
                "last_audit": "2026-06-20",
                "next_audit": "2026-12-20",
                "trend": "improving",
            },
            {
                "id": "iso-14001",
                "name": "ISO 14001:2015",
                "description": "Environmental Management System",
                "score": 85,
                "status": "compliant",
                "requirements_total": 42,
                "requirements_met": 36,
                "gaps": 6,
                "last_audit": "2026-05-15",
                "next_audit": "2026-11-15",
                "trend": "stable",
            },
            {
                "id": "osha-1910",
                "name": "OSHA 1910",
                "description": "General Industry Standards",
                "score": 78,
                "status": "partial",
                "requirements_total": 65,
                "requirements_met": 51,
                "gaps": 14,
                "last_audit": "2026-04-10",
                "next_audit": "2026-10-10",
                "trend": "declining",
            },
            {
                "id": "api-510",
                "name": "API 510",
                "description": "Pressure Vessel Inspection",
                "score": 65,
                "status": "at_risk",
                "requirements_total": 35,
                "requirements_met": 23,
                "gaps": 12,
                "last_audit": "2026-03-20",
                "next_audit": "2026-09-20",
                "trend": "declining",
            },
            {
                "id": "asme-pcc2",
                "name": "ASME PCC-2",
                "description": "Repair of Pressure Equipment",
                "score": 88,
                "status": "compliant",
                "requirements_total": 28,
                "requirements_met": 25,
                "gaps": 3,
                "last_audit": "2026-06-01",
                "next_audit": "2026-12-01",
                "trend": "improving",
            },
            {
                "id": "nfpa-70e",
                "name": "NFPA 70E",
                "description": "Electrical Safety in the Workplace",
                "score": 71,
                "status": "partial",
                "requirements_total": 27,
                "requirements_met": 19,
                "gaps": 8,
                "last_audit": "2026-05-01",
                "next_audit": "2026-11-01",
                "trend": "stable",
            },
        ],
    }


@router.get("/gaps")
async def get_compliance_gaps():
    return {
        "gaps": [
            {
                "id": "gap-001",
                "regulation": "API 510",
                "requirement": "External visual inspection of pressure vessels V-201, V-205, V-208",
                "status": "non_compliant",
                "risk_level": "high",
                "gap_description": "Three pressure vessels are overdue for external inspection by more than 30 days",
                "due_date": "2026-05-22",
                "days_overdue": 31,
                "recommended_action": "Schedule immediate external inspection with certified API 510 inspector",
                "estimated_cost": 15000,
                "responsible": "John Chen",
            },
            {
                "id": "gap-002",
                "regulation": "OSHA 1910",
                "requirement": "Annual LOTO procedure review per OSHA 1910.147(c)(6)",
                "status": "non_compliant",
                "risk_level": "high",
                "gap_description": "Electrical and Mechanical departments have not completed annual LOTO procedure review. Last review: March 2025",
                "due_date": "2026-03-15",
                "days_overdue": 99,
                "recommended_action": "Schedule immediate LOTO procedure review for both departments",
                "estimated_cost": 5000,
                "responsible": "Sarah Kim",
            },
            {
                "id": "gap-003",
                "regulation": "NFPA 70E",
                "requirement": "Arc flash hazard analysis update after electrical system modifications",
                "status": "non_compliant",
                "risk_level": "high",
                "gap_description": "Arc flash study for Substation B not updated after MOC #2026-008 modifications completed in April 2026",
                "due_date": "2026-05-01",
                "days_overdue": 52,
                "recommended_action": "Commission updated arc flash study from qualified electrical engineer",
                "estimated_cost": 25000,
                "responsible": "Mike Torres",
            },
            {
                "id": "gap-004",
                "regulation": "ISO 14001",
                "requirement": "Hazardous waste disposal documentation",
                "status": "partial",
                "risk_level": "medium",
                "gap_description": "Waste disposal records for Zone C are incomplete for Q2 2026. Missing manifests for 3 shipments.",
                "due_date": "2026-06-30",
                "days_overdue": 0,
                "recommended_action": "Locate and file missing waste manifests. Contact waste hauler for copies.",
                "estimated_cost": 2000,
                "responsible": "Sarah Kim",
            },
            {
                "id": "gap-005",
                "regulation": "OSHA 1910",
                "requirement": "Process Safety Management - P&ID updates after Management of Change",
                "status": "partial",
                "risk_level": "medium",
                "gap_description": "4 P&IDs not updated after MOC #2026-015 for Zone B piping modifications",
                "due_date": "2026-07-15",
                "days_overdue": 0,
                "recommended_action": "Update P&IDs P-101-A, P-102-B, P-103-A, P-104-C to reflect field changes",
                "estimated_cost": 8000,
                "responsible": "Mike Torres",
            },
            {
                "id": "gap-006",
                "regulation": "ISO 45001",
                "requirement": "Hazard identification and risk assessment procedures",
                "status": "partial",
                "risk_level": "low",
                "gap_description": "3 minor non-conformities in hazard identification documentation. Risk assessments for 2 new chemical processes pending.",
                "due_date": "2026-08-01",
                "days_overdue": 0,
                "recommended_action": "Complete risk assessments for new processes and update hazard register",
                "estimated_cost": 3000,
                "responsible": "Sarah Kim",
            },
        ],
        "summary": {
            "total_gaps": 6,
            "high_risk": 3,
            "medium_risk": 2,
            "low_risk": 1,
            "total_estimated_cost": 58000,
            "avg_days_overdue": 30,
        },
    }


@router.get("/audit-report")
async def generate_audit_report():
    return {
        "report": {
            "title": "ForgeIQ Compliance Audit Report",
            "generated_at": "2026-06-22T14:30:00Z",
            "period": "Q2 2026",
            "overall_score": 78.4,
            "executive_summary": "The organization maintains a reasonable compliance posture with an overall score of 78.4%. ISO 45001 and ASME PCC-2 compliance are strong. However, API 510 pressure vessel inspection backlog and OSHA LOTO procedure reviews require immediate attention. Three high-risk gaps have been identified that should be addressed within 30 days to avoid potential regulatory action.",
            "risk_rating": "Medium-High",
            "recommendations": [
                "Prioritize API 510 vessel inspections for V-201, V-205, V-208",
                "Complete overdue LOTO procedure reviews immediately",
                "Commission updated arc flash study for Substation B",
                "Implement automated compliance tracking to prevent future gaps",
                "Schedule quarterly compliance reviews with department heads",
            ],
        },
    }
